### ISSUE TITLE
Consider using epdf

### ISSUE THREAD

**Issue by mitranim** [Janpot/electron-pdf#5]
[`epdf`](https://github.com/Mitranim/epdf) is a replacement for the `electron-pdf` library used by this Docker image. I wrote it to address various issues with `electron-pdf` such as: bloated, difficult to use API; forced Markdown detection; no obvious way to cancel work; loss of stability when used for a long period inside an Electron process.

Additional note: the server shouldn't be run as an Electron process, but as a Node.js process that spawns an Electron for each render. In my experience, this is far more stable; running each render in the same Electron process leads to increasing latency due to apparent internal leaks.

`epdf` also allows to cancel rendering. This should be done when the incoming HTTP request prematurely ends to reduce the load on the server.

This is just a suggestion. I could do a pull request with these changes if you want.

**Comment by mitranim** [comment]
Haha nevermind, something must have mixed in my head, and I must have confused this with another similar image. Now I'm confused which one I used last time. Either way, I'll leave this up for now.

**Comment by Janpot** [comment]
I'm not really maintaining this at the moment. If you want to contribute, electron should be replaced by Chrome headless here.

**Comment by mitranim** [comment]
Yeah good point. Should look into it.
