### ISSUE TITLE
Would you be willing to add a license? Thanks!

### ISSUE THREAD

**Issue by WriterDuet** [Janpot/electron-pdf#6]
This repo doesn't currently specify its licensing. An MIT or Apache license would be much appreciated!!

**Comment by Janpot** [comment]
Feel free to open a PR with MIT license. I must warn you though, I'm not maintaining this repo, it was mostly created as an experiment.
Anno 2020 I would definitely recommend using [`puppeteer`](https://www.npmjs.com/package/puppeteer) for this task instead.

**Comment by kbgar24** [comment]
@Janpot Thanks! The PR has been opened: https://github.com/Janpot/electron-pdf/pull/7

Appreciate the recommendation. We initially went that route but after considerable testing **electron-pdf** appears to offer a more faithful/pixel-perfect reproduction of Chrome PDFs than **puppeteer**.
